from __future__ import annotations

from typing import Any

class TachyonEngine:
    def __init__(self, owner: Any, mode: str = "multiversal") -> None: ...
    def list_labels(self) -> list[str]: ...
    def create_moment(self, label: str) -> None: ...
    def move_to(self, label: str) -> None: ...
    def move_to_creation(self) -> None: ...
    def undo(self) -> None: ...
    def redo(self) -> None: ...
    def log_update_attr(self, name: str, old_value: Any, new_value: Any) -> None: ...
    def log_plugin_op(self, path: str, adapter_name: str, delta_blob: Any) -> None: ...
    def log_list_pop(self, path: str, index: int, popped_value: Any) -> None: ...
    def log_list_insert(self, path: str, index: int, value: Any) -> None: ...
    def log_list_remove(self, path: str, value: Any) -> None: ...
    def log_list_replace(
        self, path: str, index: int, old_value: Any, new_value: Any
    ) -> None: ...
    def log_dict_update(
        self, path: str, key: Any, old_value: Any, new_value: Any
    ) -> None: ...
    def log_dict_delete(self, path: str, key: Any, old_value: Any) -> None: ...
    def extract_timeline(self, label: str) -> list[dict[str, Any]]: ...
    def current_branch(self) -> str: ...
    def current_node(self) -> int: ...
    def create_branch(self, label: str) -> None: ...
    def switch_branch(self, label: str) -> None: ...
    def list_branches(self) -> list[str]: ...
    def list_nodes(self) -> list[str]: ...
    def label_node(self, label: str) -> None: ...
    def delete_branch(self, label: str) -> None: ...

class TrackedList:
    def __init__(
        self, initial: list[Any], engine: TachyonEngine, name: str
    ) -> None: ...
    def append(self, value: Any) -> None: ...
    def pop(self, index: int | None = None) -> Any: ...
    def __getitem__(self, index: int) -> Any: ...
    def __setitem__(self, index: int, value: Any) -> None: ...
    def __len__(self) -> int: ...
    def insert(self, index: int, value: Any) -> None: ...
    def remove(self, value: Any) -> None: ...
    def clear(self) -> None: ...
    def extend(self, values: list[Any]) -> None: ...
    def __iter__(self) -> Any: ...
    def __contains__(self, value: Any) -> bool: ...
    def __delitem__(self, index: int) -> None: ...

class TrackedDict:
    def __init__(
        self, initial: dict[str, Any], engine: TachyonEngine, name: str
    ) -> None: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def __contains__(self, key: str) -> bool: ...
    def __iter__(self) -> Any: ...
    def keys(self) -> list[str]: ...
    def __len__(self) -> int: ...
    def get(self, key: str, default: Any | None = None) -> Any: ...
