from __future__ import annotations

from collections.abc import Callable
from typing import Any

class TachyonEngine:
    def __init__(
        self, owner: Any, mode: str = "multiversal", max_nodes: int = 50000
    ) -> None: ...
    @property
    def owner(self) -> Any: ...
    def get_graph_data(self) -> list[dict[str, Any]]: ...
    def list_labels(self) -> list[str]: ...
    def create_moment(self, label: str) -> None: ...
    def move_to(self, label: str) -> None: ...
    def move_to_creation(self) -> None: ...
    def undo(self) -> None: ...
    def redo(self) -> None: ...
    def gc(self) -> None: ...
    def prune(self) -> None: ...
    def log_update_attr(self, name: str, old_value: Any, new_value: Any) -> None: ...
    def log_plugin_op(self, path: str, adapter_name: str, delta_blob: Any) -> None: ...
    def log_list_pop(self, path: str, index: int, popped_value: Any) -> None: ...
    def log_list_insert(self, path: str, index: int, value: Any) -> None: ...
    def log_list_remove(self, path: str, value: Any) -> None: ...
    def log_list_replace(
        self, path: str, index: int, old_value: Any, new_value: Any
    ) -> None: ...
    def log_dict_update(
        self, path: str, key: Any, old_value: Any, new_value: Any
    ) -> None: ...
    def log_dict_delete(self, path: str, key: Any, old_value: Any) -> None: ...
    def extract_timeline(
        self, label: str | None = None, filter_attr: list[str] | None = None
    ) -> list[dict[str, Any]]: ...
    def find_nodes_by_metadata(self, key: str, value: Any) -> list[int]: ...
    def squash_branch(self, label: str | None = None) -> None: ...
    def merge_branch(
        self, source_label: str, strategy: str | Callable[..., Any] | None = None
    ) -> None: ...
    @property
    def current_branch(self) -> str: ...
    @property
    def current_node(self) -> int: ...
    def create_branch(self, label: str) -> None: ...
    def switch_branch(self, label: str) -> None: ...
    def list_branches(self) -> list[str]: ...
    def list_nodes(self) -> list[str]: ...
    def label_node(self, label: str) -> None: ...
    def delete_branch(self, label: str) -> None: ...
    def get_node_id(self, label: str) -> int | None: ...
    def set_metadata(self, key: str, value: Any) -> None: ...
    def get_metadata(self, key: str, node_id: int | None = None) -> Any: ...
    def get_metadata_keys(self, node_id: int | None = None) -> list[str]: ...
    def get_metadata_values(self, node_id: int | None = None) -> list[Any]: ...
    def get_metadata_items(
        self, node_id: int | None = None
    ) -> list[tuple[str, Any]]: ...
    def get_graph_state(self) -> dict[str, Any]: ...
    def set_graph_state(self, state: dict[str, Any]) -> None: ...
    def sync_from_root(self) -> None: ...
    def save(self, path: str) -> None: ...
    def load(self, path: str) -> None: ...
    def squash(self, start_label: str, end_label: str) -> None: ...
    def get_diff(self, start_label: str, end_label: str) -> dict[str, Any]: ...

class TrackedListCore:
    def __init__(self, engine: TachyonEngine, name: str) -> None: ...
    def log_insert(self, index: int, value: Any) -> None: ...
    def log_pop(self, index: int, value: Any) -> None: ...
    def log_replace(self, index: int, old_value: Any, new_value: Any) -> None: ...
    def log_clear(self, old_values: list[Any]) -> None: ...
    def log_extend(self, new_values: list[Any]) -> None: ...

class TrackedDictCore:
    def __init__(self, engine: TachyonEngine, name: str) -> None: ...
    def log_update(
        self,
        keys: list[str],
        old_values: list[Any],
        new_values: list[Any],
    ) -> None: ...
    def log_delete(self, key: str, old_value: Any) -> None: ...
    def log_clear(self, keys: list[str], old_values: list[Any]) -> None: ...
    def log_pop(self, key: str, old_value: Any) -> None: ...
