from __future__ import annotations

from typing import Any

class TachyonEngine:
    def __init__(self, owner: Any, mode: str = "multiversal") -> None: ...
    @property
    def owner(self) -> Any: ...
    def list_labels(self) -> list[str]: ...
    def create_moment(self, label: str) -> None: ...
    def move_to(self, label: str) -> None: ...
    def move_to_creation(self) -> None: ...
    def undo(self) -> None: ...
    def redo(self) -> None: ...
    def log_update_attr(self, name: str, old_value: Any, new_value: Any) -> None: ...
    def log_plugin_op(self, path: str, adapter_name: str, delta_blob: Any) -> None: ...
    def log_list_pop(self, path: str, index: int, popped_value: Any) -> None: ...
    def log_list_insert(self, path: str, index: int, value: Any) -> None: ...
    def log_list_remove(self, path: str, value: Any) -> None: ...
    def log_list_replace(
        self, path: str, index: int, old_value: Any, new_value: Any
    ) -> None: ...
    def log_dict_update(
        self, path: str, key: Any, old_value: Any, new_value: Any
    ) -> None: ...
    def log_dict_delete(self, path: str, key: Any, old_value: Any) -> None: ...
    def extract_timeline(self, label: str) -> list[dict[str, Any]]: ...
    @property
    def current_branch(self) -> str: ...
    @property
    def current_node(self) -> int: ...
    def create_branch(self, label: str) -> None: ...
    def switch_branch(self, label: str) -> None: ...
    def list_branches(self) -> list[str]: ...
    def list_nodes(self) -> list[str]: ...
    def label_node(self, label: str) -> None: ...
    def delete_branch(self, label: str) -> None: ...

class TrackedListCore:
    def __init__(self, engine: TachyonEngine, name: str) -> None: ...
    def log_insert(self, index: int, value: Any) -> None: ...
    def log_pop(self, index: int, value: Any) -> None: ...
    def log_replace(self, index: int, old_value: Any, new_value: Any) -> None: ...
    def log_clear(self, old_values: list[Any]) -> None: ...
    def log_extend(self, new_values: list[Any]) -> None: ...

class TrackedDictCore:
    def __init__(self, engine: TachyonEngine, name: str) -> None: ...
    def log_update(
        self,
        keys: list[str],
        old_values: list[Any],
        new_values: list[Any],
    ) -> None: ...
    def log_delete(self, key: str, old_value: Any) -> None: ...
    def log_clear(self, keys: list[str], old_values: list[Any]) -> None: ...
    def log_pop(self, key: str, old_value: Any) -> None: ...
