name: Janus CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: "3.12"

      - name: Install Python Dependencies
        run: uv sync

      - name: Run Cargo Clippy
        run: cargo clippy -- -D warnings

      - name: Build Janus (Maturin)
        run: uv run maturin develop

      - name: Run PyTest
        run: uv run pytest tests/ -v
